export const GET_ERRORS = "GET_ERRORS";
export const USER_LOADING = "USER_LOADING";
export const SET_CURRENT_USER = "SET_CURRENT_USER";
export const PUSH_USER_APPOINTMENT_DATE = "PUSH_USER_APPOINTMENT_DATE";